.\" Manpage for baalue_gui
.\" Contact thorsten.johannvorderbrueggen@t-online.de to correct errors or typos.
.TH baalue 1 "20 Jul 2016" "0.0.1" "baalue_gui man page"
.SH NAME
baalue_gui
\-\- the baalue_gui
.SH SYNOPSIS
.PP
.SH DESCRIPTION
This functions are part of the
.BR baalue_sdk
(https://github.com/tjohann/baalue)
.PP
The baalue gui
.PP
.SH FILES
.BR baalue.c
\- function implementation
.br
.BR baalue.h
\- interface header
.br
.PP
.SH OPTIONS
None
.PP
.SH BUGS
No known bugs
.PP
.SH "SEE ALSO"
.BR baalued(1)
.PP
.BR baalue(1)
.PP
.BR libbaalue(3)
.PP
.SH AUTHOR
Thorsten Johannvorderbrueggen
.br
Email: \fB<thorsten.johannvorderbrueggen@t-online.de> \fP
